### ISSUE TITLE
Filter out empty `msgid` entries

### ISSUE THREAD

**Issue by mgeisler** [google/mdbook-i18n-helpers#64]
I tried running `mdbook-xgettext` on the [Rust Book](https://github.com/rust-lang/book). After removing formatting from the SUMMARY.md file, I end up with a `messages.pot` file which is almost correct:

```shell
% msgcat -o po/messages.pot po/messages.pot
po/messages.pot:1660: duplicate message definition...
po/messages.pot:3: ...this is the location of the first definition
msgcat: found 1 fatal error
```

The problem is this entry:

```gettext
#: src/appendix-04-useful-development-tools.md:120
#: src/appendix-04-useful-development-tools.md:149
msgid ""
msgstr ""
```

which in turn originates from a [non-empty HTML tag](https://github.com/rust-lang/book/blob/main/src/appendix-04-useful-development-tools.md?plain=1#L149):

```markdown
<span class="filename">Filename: src/main.rs</span>
```

The empty `msgid` is also produced by [empty HTML tags](https://github.com/rust-lang/book/blob/main/src/ch00-00-introduction.md?plain=1#L169):

```markdown
<span id="ferris"></span>
```

We should handle such entries correctly. This would mean

1. Ensure we don't add duplicate entries to the PO file. This is perhaps something that need fixing in [polib](https://github.com/brettdong/polib).
2. Perhaps we should extract the text inside inline HTML tags such as the `span` above?

**Comment by Demian101** [comment]
COOL！Thank you very much~  OK, Maybe it is because I used `cloud-tranlate` to gen the `en.po` .. 

**I aslo get another question maybe I should ask in the `cloud-tranlate` repo :**  

when I finished use `cloud-tranlate` repo  to translate and ran :
```bash
msgmerge --update po/en.po po/messages.pot
```
<img width="785" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/520a7665-58f0-4379-b4c7-854cf1e6d14f">

<img width="719" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/a1798330-ee60-446e-85a5-960a4986ce54">
